=== SergioPA11/Playita/XmlSchema_playita.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.playitaCorra.com/"
           xmlns="https://www.playitaCorra.com/"
           elementFormDefault="qualified">

    <xs:element name="predictions" type="predictions-type"/>
    
    <xs:complexType name="predictions-type">
        <xs:sequence>
            <xs:element name="prediction" maxOccurs="unbounded" type="prediction-type"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="prediction-type">
        <xs:sequence>
            <xs:element name="day" type="xs:integer"/>
            <xs:element name="sky_state" type="sky_state-type"/>
            <xs:element name="wind" type="wind-type"/>
            <xs:element name="surge" type="surge-type"/>
            <xs:element name="t_max" type="xs:integer"/>
            <xs:element name="s_thermal" type="s_thermal-type"/>
            <xs:element name="t_water" type="xs:integer"/>
            <xs:element name="uv_max" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="sky_state-type">
        <xs:sequence>
            <xs:element name="f1" type="xs:integer"/>
            <xs:element ref="descripcion1"/>
            <xs:element name="f2" type="xs:integer"/>
            <xs:element ref="descripcion2"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="wind-type">
        <xs:sequence>
            <xs:element name="f1" type="xs:integer"/>
            <xs:element ref="descripcion1"/>
            <xs:element name="f2" type="xs:integer"/>
            <xs:element ref="descripcion2"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="surge-type">
        <xs:sequence>
            <xs:element name="f1" type="xs:integer"/>
            <xs:element ref="descripcion1"/>
            <xs:element name="f2" type="xs:integer"/>
            <xs:element ref="descripcion2"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="s_thermal-type">
        <xs:sequence>
            <xs:element name="f1" type="xs:integer"/>
            <xs:element ref="descripcion1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="descripcion1" type="descripcion-type"/>
    <xs:element name="descripcion2" type="descripcion-type"/>
    
    <xs:simpleType name="descripcion-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="muy nuboso"/>
            <xs:enumeration value="despejado"/>
            <xs:enumeration value="flojo"/>
            <xs:enumeration value="dÃ©bil"/>
            <xs:enumeration value="suave"/>
            <xs:enumeration value="nuboso"/>
            <xs:enumeration value="moderado"/>
            <xs:enumeration value="fuerte"/>
            <xs:enumeration value="muy fuerte"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== SergioPA11/Playita/Playita_output.xml
<?xml version="1.0" encoding="UTF-8"?>
<predictions xmlns="https://www.playitaCorra.com/"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://www.playitaCorra.com/ XmlSchema_playita.xsd">
    <prediction>
        <day>20200403</day>
        <sky_state>
            <f1>120</f1>
            <descripcion1>muy nuboso</descripcion1>
            <f2>100</f2>
            <descripcion2>despejado</descripcion2>
        </sky_state>
        <wind>
            <f1>210</f1>
            <descripcion1>flojo</descripcion1>
            <f2>210</f2>
            <descripcion2>flojo</descripcion2>
        </wind>
        <surge>
            <f1>310</f1>
            <descripcion1>débil</descripcion1>
            <f2>310</f2>
            <descripcion2>débil</descripcion2>
        </surge>
        <t_max>21</t_max>
        <s_thermal>
            <f1>310</f1>
            <descripcion1>suave</descripcion1>
        </s_thermal>
        <t_water>20</t_water>
        <uv_max>8</uv_max>
    </prediction>
    <prediction>
        <day>20200404</day>
        <sky_state>
            <f1>120</f1>
            <descripcion1>muy nuboso</descripcion1>
            <f2>110</f2>
            <descripcion2>nuboso</descripcion2>
        </sky_state>
        <wind>
            <f1>210</f1>
            <descripcion1>flojo</descripcion1>
            <f2>210</f2>
            <descripcion2>flojo</descripcion2>
        </wind>
        <surge>
            <f1>310</f1>
            <descripcion1>débil</descripcion1>
            <f2>310</f2>
            <descripcion2>débil</descripcion2>
        </surge>
        <t_max>23</t_max>
        <s_thermal>
            <f1>310</f1>
            <descripcion1>suave</descripcion1>
        </s_thermal>
        <t_water>19</t_water>
        <uv_max>8</uv_max>
    </prediction>
    <prediction>
        <day>20200405</day>
        <sky_state>
            <f1>120</f1>
            <descripcion1>muy nuboso</descripcion1>
            <f2>120</f2>
            <descripcion2>muy nuboso</descripcion2>
        </sky_state>
        <wind>
            <f1>210</f1>
            <descripcion1>flojo</descripcion1>
            <f2>220</f2>
            <descripcion2>moderado</descripcion2>
        </wind>
        <surge>
            <f1>310</f1>
            <descripcion1>débil</descripcion1>
            <f2>310</f2>
            <descripcion2>débil</descripcion2>
        </surge>
        <t_max>23</t_max>
        <s_thermal>
            <f1>310</f1>
            <descripcion1>suave</descripcion1>
        </s_thermal>
        <t_water>20</t_water>
        <uv_max>9</uv_max>
    </prediction>
</predictions>
